name: task1 - Build and test

on:
  push:
    paths:
      - task1/**

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        defaults:
              run:
                working-directory: ./task1

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "zulu"

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

            - name: Build & test with Gradle
              run: ./gradlew build

